### ISSUE TITLE
Referenced locals can never live in a register (was ykpack::LocalDecl is too restrictive)

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#316]
The current definition is:

```rust
pub struct LocalDecl {
    pub ty: TypeId,
    /// If true this local variable is at some point referenced, and thus should be allocated on
    /// the stack and never in a register.
    pub referenced: bool,
}
```

The `referenced` field is too strict. For example, imagine if I have this code:

```rust
let x = 0;
for _ in ... {
  // Something involving x where we'd really like to have it in a register
}
f(&x);
```

I don't want `x` to be on the stack for the whole function: I want it to be in a register when it can be, and on the stack when it needs to be. The trace optimiser should make up its own mind about when, and for how long, something can be on the stack or in a register. In other words, I think the `referenced` field is an unnecessary pessimisation.

**Comment by ltratt** [comment]
In the x86_64 compiler we have this:

```
    fn can_live_in_register(decl: &LocalDecl) -> bool {
        if decl.is_referenced() {
            // We must allocate it on the stack so that we can reference it.
            return false;
        }
```

which I think confirms my suspicions that this is a premature pesimisation.

**Comment by ptersilie** [comment]
I think this might have been one of the liberties we've taken early on to make our life easier, but I agree that this is probably too restrictive. Since @vext01 implemented this, let's see if he can remember if there was a deeper reason for this.

**Comment by vext01** [comment]
Currently locals can't move once an allocation has been decided, and if a local is referenced, it is doomed to live on the stack for its whole life.

This is simple and correct, but (as Laurie points out) sub-optimal.

In the early days we were too ambitious and tried to allow locals to move. This ended badly: the problem was that it was too easy to use stale register allocation information. E.g.:

```
let loc = self.local_to_location(l1);
// Other stuff, but the allocation of `l1` moves.
self.store(loc, ...); // <-- hilarity ensues.
```

And salt in the wound is that this kind of bug is very hard to track down.

If we wanted to fix this, rather than expecting developers to correctly re-fetch potentially moved allocations, I'd recommend thinking about an extension to our allocation API which raises some kind of error if stale allocation data is accessed: some kind of box which gets invalidated when an allocation moves.

**Comment by ltratt** [comment]
I think the problem is that we've got our compile-time/run-time levels confused: the `referenced` bool makes a decision at compile-time that should be left to run-time (when we'll find that either a) for a given trace we don't reference the variable so we never need to move something to the stack b) we only need to move something later on in a trace). I'm fine with this as a temporary hack, but assuming that's what it is, we should probably add a `FIXME` to make that clear.

**Comment by vext01** [comment]
> I think the problem is that we've got our compile-time/run-time levels confused.

I don't think we were confused. It's another of these "we did what was easiest first" scenarios. Under the current assumption (that locals don't move), it makes sense for this to be static. If you want more clever dynamic allocation with moving, then we of course must do it at runtime.

FWIW we have the ability to detect a reference being made: there is a dedicated bytecode for it. I think `MkRef`. But I would insist on some way of preventing us from using stale allocations.

> we should probably add a FIXME

By all means.

**Comment by vext01** [comment]
Closing, as this is for the old yk design.
