### ISSUE TITLE
Tests don't build

### ISSUE THREAD

**Issue by ltratt** [ykjit/yk#470]
Any non-trivial test in `ykrt/src/mt.rs` such as:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hot_threshold_passed() {
        let hot_thrsh: HotThreshold = 1500;
        let mt = MT::global();
        let loc = Location::new();
        for i in 0..hot_thrsh {
            MT::transition_location(&loc);
        }
    }
}
```

causes a linker error:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/ltratt/yk/target/debug/deps/ykrt-e549a82218bf7b47.13mjq23so3byahxg.rcgu.o"
<vast swathes of stuff cut>
          /home/ltratt/yk/ykllvmwrap/src/ykllvmwrap.cc:186: undefined reference to `__ykutil_get_llvmbc_section'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `ykrt` (lib test) generated 2 warnings
error: could not compile `ykrt` due to previous error; 2 warnings emitted
```

I wonder if this is something to do with the `thread_local!` we use?

**Comment by vext01** [comment]
We can't yet use the tracer with Rust programs yet. There are lots of details, some of which I've forgotten, but I can investigate tomorrow.

**Comment by vext01** [comment]
OK, I understand what's going on here now. There is an implicit circular dependency which *is* resolved when the test is written in C, but not when the test is written in Rust.

Brace yourself.

![image](https://user-images.githubusercontent.com/604955/148924453-09ee4f6c-ab39-4246-a147-a6578f3c9215.png)

`ykllvmwrap` implicitly depends on `ykcapi` for `__ykutil_get_llvmbc_sec()` and when the test is written in C, the test links `ykcapi`, thus pulling in `ykrt` and `ykllvmwrap` and all symbols are resolved.

When you use `transition_location` in a Rust test in `ykrt`, you pull in `ykllvmwrap` via `yktrace`, but `ykcapi` is not loaded at the same time, so `__ykutil_get_llvmbc_sec()` is undefined.

We might be tempted to make `ykllvmwrap` depend on `ykcapi`, but that makes a circular cargo dependency, you can't do that.

This all goes back to Rust linkage limitations when talking to C code. If you aren't careful, you end up with multiple copies of the Rust std lib linked and the symbols clash. We [discussed it a while back](https://github.com/ykjit/yk/pull/335) and concluded that the most sane way to do things is to have one crate responsible for exporting C symbols (`ykcapi`), then there can only ever be one copy of the Rust std lib.

However, as we see here, we can hit other problems.

Potential solutions:
 - Write your test in C. This would require exporting everything you need over the C ABI. From experience, this is annoying.
 - Rewrite `__ykutil_get_llvmbc_sec()` in C and put it directly in `ykllvmwrap`, thus removing the implicit dependency between `ykllvmwrap` and `ykcapi`. This is also annoying.
 - Make it so that `ykrt` doesn't invoke the trace compiler. Sounds annoying.
 - Try to fix it another way with "out of the box thinking".

I'll spend a bit of time on "out of the box thinking" and if I fail, fall back on re-writing `__ykutil_get_llvmbc_sec()` in C.

**Comment by ltratt** [comment]
> if I fail, fall back on re-writing __ykutil_get_llvmbc_sec() in C.

Of the options you've outlined, that sounds the best (or maybe: least worst).
